# -*- coding: utf-8 -*-
"""MDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1peZQ4dj1pGnUsTYXF-cv0iaF2JdyExEb
"""

# -*- coding: utf-8 -*-
"""Versión completa con MongoDB + correcciones de Sí/No"""

import base64
import secrets
from collections import defaultdict
from pymongo import MongoClient

# ================================
# 🔵  CONEXIÓN A MONGODB
# ================================
# ⚠️ REEMPLAZA TU CADENA DE MONGODB AQUÍ
MONGO_URI = "mongodb+srv://tavo_user:1234567#@cluster0.cjx2xfb.mongodb.net/?appName=Cluster0"
client = MongoClient(MONGO_URI)
db = client["bricos_db"]
coleccion = db["candidatos"]

# ================================
# 🔵  PARÁMETROS
# ================================
NUM_PREGUNTAS_TECNICAS = 12
NUM_PREGUNTAS_BLANDAS = 13
PUNTAJE_MINIMO_BLANDAS = 0.45

# ================================
# 🔵  CLASE RSA SIMULADA
# ================================
class RSAKeySimulada:
    def __init__(self):
        self.public_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")
        self.private_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")

def cifrar_rsa_simulado(datos, clave_publica):
    datos_codificados = base64.urlsafe_b64encode(datos.encode("utf-8")).decode("utf-8")
    return f"RSA-256:{clave_publica[:16]}...{datos_codificados[:40]}..."

# ================================
# 🔵  PREGUNTAS TÉCNICAS
# ================================
PREGUNTAS_TECNICAS = [
    "¿Sabe realizar inventarios físicos y conteos rápidos de material de construcción?",
    "¿Ha utilizado algún software de Punto de Venta (POS) o sistema de facturación electrónica?",
    "¿Sabe leer e interpretar una hoja de ruta o usar GPS para optimizar entregas?",
    "¿Tiene experiencia o conoce el manejo básico de un montacargas o patín hidráulico?",
    "¿Puede identificar y diferenciar los tipos de cemento, varilla y arena comunes en la construcción?",
    "¿Sabe cómo se calcula el volumen o área de un material (ej. m³ de arena, m² de loseta)?",
    "¿Se siente cómodo manejando una terminal bancaria y realizando cobros con tarjeta?",
    "¿Puede verificar y cotejar una orden de compra contra el material físico que se va a cargar?",
    "¿Conoce las normas básicas de seguridad para cargar y descargar materiales pesados?",
    "¿Tiene conocimientos básicos de uso de hojas de cálculo (Excel, Google Sheets) para reportes?",
    "¿Sabe realizar el mantenimiento básico o limpieza de herramientas y equipos de trabajo?",
    "¿Puede calcular rápidamente el cambio para un pago en efectivo?"
]

PREGUNTAS_BLANDAS = [
    "¿Mantiene la calma y es cortés al tratar con un cliente enojado o impaciente?",
    "¿Se adapta fácilmente a los cambios de tareas o prioridades de última hora?",
    "¿Ofrece ayuda a sus compañeros sin que se lo pidan?",
    "¿Es puntual y respeta estrictamente los horarios?",
    "¿Acepta retroalimentación sin ponerse a la defensiva?",
    "¿Se enfoca en soluciones en lugar de culpar a otros?",
    "¿Es proactivo buscando tareas pendientes?",
    "¿Se comunica de manera clara y concisa?",
    "¿Trabaja bien bajo presión?",
    "¿Su honestidad y ética son inquebrantables?",
    "¿Prioriza la seguridad ante todo?",
    "¿Propone mejoras a procesos ineficientes?",
    "¿Se siente cómodo pidiendo al cliente verificar la carga/ticket?"
]

# ================================
# 🔵  ÁREAS
# ================================
AREAS = {
    "CARGADOR":         [0, 3, 4, 7, 8],
    "VENTAS/COBRANZA":  [1, 6, 11],
    "REPARTIDOR":       [2, 3, 7, 8],
    "LIMPIEZA":         [10],
    "ADMINISTRATIVO":   [9, 1, 5]
}

def asignar_area(respuestas):
    conteo = defaultdict(int)
    for area, indices in AREAS.items():
        conteo[area] = sum(1 for i in indices if respuestas[i] == "Sí")

    if not any(conteo.values()):
        return max(AREAS, key=lambda a: len(AREAS[a]))

    return max(conteo, key=conteo.get)

# ================================
# 🔵  SELECCIÓN DE ÁREA DESEADA
# ================================
def seleccionar_area_deseada():
    opciones = {
        "1": "CARGADOR",
        "2": "VENTAS/COBRANZA",
        "3": "REPARTIDOR",
        "4": "LIMPIEZA",
        "5": "ADMINISTRATIVO"
    }

    print("\n--- PUESTO AL QUE DESEAS APLICAR ---")
    for k, v in opciones.items():
        print(f"{k}. {v}")

    while True:
        eleccion = input("Elige una opción (1-5): ").strip()
        if eleccion in opciones:
            return opciones[eleccion]
        print("Opción no válida.")

# ================================
# 🔵  DATOS PERSONALES
# ================================
def pedir_datos_personales():
    def pedir(m):
        while True:
            x = input(m).strip()
            if x:
                return x
            print("No puede quedar vacío.")

    print("\n--- DATOS PERSONALES ---")
    return {
        "nombre": pedir("Nombre completo: "),
        "edad": pedir("Edad: "),
        "sexo": pedir("Sexo (M/F/Otro): "),
        "correo": pedir("Correo electrónico (se cifrará): "),
        "telefono": pedir("Número de teléfono (se cifrará): ")
    }

# ================================
# 🔵  CUESTIONARIOS (Sí / No corregido)
# ================================
def realizar_cuestionario(preguntas, tipo):
    puntaje = 0
    respuestas = []

    print(f"\n--- HABILIDADES {tipo.upper()} ---")
    for i, p in enumerate(preguntas):
        while True:
            r = input(f"{i+1}. {p} (S/N): ").upper().strip()
            if r in ("S", "N"):
                respuestas.append("Sí" if r == "S" else "No")
                if r == "S":
                    puntaje += 1
                break
            print("Respuesta inválida.")
    return puntaje, respuestas

# ================================
# 🔵  EVALUACIÓN
# ================================
def evaluar(pt_tecnico, pt_blando):
    return (
        (pt_blando / NUM_PREGUNTAS_BLANDAS) >= PUNTAJE_MINIMO_BLANDAS,
        (pt_tecnico / NUM_PREGUNTAS_TECNICAS) * 100,
        (pt_blando / NUM_PREGUNTAS_BLANDAS) * 100
    )

# ================================
# 🔵  PROCESO PRINCIPAL
# ================================
def iniciar_proceso_seleccion():
    print("\n========================================")
    print("    🌟 SISTEMA DE SELECCIÓN MUCHACHAM 🌟")
    print("========================================")

    datos = pedir_datos_personales()
    area_deseada = seleccionar_area_deseada()

    key = RSAKeySimulada()
    datos_cifrados = cifrar_rsa_simulado(
        f"Email:{datos['correo']}|Tel:{datos['telefono']}",
        key.public_key
    )

    pt_tecnico, resp_tecnicas = realizar_cuestionario(PREGUNTAS_TECNICAS, "TÉCNICAS")
    pt_blando, resp_blandas = realizar_cuestionario(PREGUNTAS_BLANDAS, "BLANDAS")

    aceptado, pct_tec, pct_bla = evaluar(pt_tecnico, pt_blando)
    area_recomendada = asignar_area(resp_tecnicas)

    # =============================
    # 🔴 GUARDAR EN MONGODB
    # =============================
    registro = {
        "nombre": datos["nombre"],
        "edad": datos["edad"],
        "sexo": datos["sexo"],
        "correo_cifrado": datos_cifrados,
        "puesto_deseado": area_deseada,
        "area_recomendada": area_recomendada,
        "puntaje_tecnico": pt_tecnico,
        "puntaje_blando": pt_blando,
        "porcentaje_tecnico": pct_tec,
        "porcentaje_blando": pct_bla,
        "aceptado": aceptado,
        "respuestas_tecnicas": resp_tecnicas,
        "respuestas_blandas": resp_blandas
    }

    coleccion.insert_one(registro)
    print("\n📌 Datos guardados correctamente en MongoDB.\n")

    print("=========== RESULTADO FINAL ===========")
    print(f"Puesto deseado:     {area_deseada}")
    print(f"Área recomendada:   {area_recomendada}")
    print(f"Técnicas: {pct_tec:.2f}% | Blandas: {pct_bla:.2f}%")
    print("Estado:", "ACEPTADO ✅" if aceptado else "NO ACEPTADO ❌")
    print("========================================")

# Ejecutar
if __name__ == "__main__":
    iniciar_proceso_seleccion()