# -*- coding: utf-8 -*-
"""MDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1peZQ4dj1pGnUsTYXF-cv0iaF2JdyExEb
"""

!pip install streamlit pymongo
import streamlit as st
from pymongo import MongoClient
from datetime import datetime
import pandas as pd

# =========================================
# 1. CONEXIÓN A MONGODB
# =========================================
MONGO_URI = "TU_CADENA_MONGODB_AQUI"
client = MongoClient(MONGO_URI)
db = client["evaluaciones"]
col = db["candidatos"]

# =========================================
# 2. PREGUNTAS
# =========================================
PREGUNTAS_TECNICAS = [
    "¿Conoce bases de datos?",
    "¿Sabe usar SQL?",
    "¿Tiene experiencia con Python?",
    "¿Sabe trabajar con APIs?",
    "¿Ha usado Git/GitHub?",
    "¿Conoce Docker?",
    "¿Ha usado frameworks web?",
    "¿Conoce análisis de datos?",
    "¿Sabe usar Excel avanzado?",
    "¿Tiene experiencia con ML?",
    "¿Comprende redes?",
    "¿Ha trabajado en la nube?"
]

PREGUNTAS_BLANDAS = [
    "¿Trabaja bien en equipo?",
    "¿Se comunica claramente?",
    "¿Tolera presión laboral?",
    "¿Tiene liderazgo?",
    "¿Es responsable?",
    "¿Llega puntual?",
    "¿Resuelve problemas?",
    "¿Aprende rápido?",
    "¿Es adaptable?",
    "¿Es creativo?",
    "¿Se organiza bien?",
    "¿Toma decisiones?",
    "¿Es proactivo?"
]

PUNTAJE_MINIMO_BLANDAS = 0.75  # 75% es el mínimo


# =========================================
# 3. NAVEGACIÓN
# =========================================
st.sidebar.title("Menú")
pagina = st.sidebar.radio("Ir a:", ["Registrar candidato", "Ver candidatos"])


# =========================================
# 4. PÁGINA: REGISTRO Y EVALUACIÓN
# =========================================
if pagina == "Registrar candidato":
    st.title("📝 Registro de Candidato")

    # --- Datos personales ---
    nombre = st.text_input("Nombre completo")
    correo = st.text_input("Correo electrónico")
    edad = st.number_input("Edad", 15, 80, 20)

    st.write("---")
    st.header("3. Cuestionario Técnico")

    respuestas_tecnicas = []
    pt_tecnico = 0

    for i, p in enumerate(PREGUNTAS_TECNICAS):
        r = st.radio(p, ["S", "N"], key=f"tec_{i}")
        respuestas_tecnicas.append(r)
        if r == "S":
            pt_tecnico += 1

    st.write("---")
    st.header("4. Cuestionario de Habilidades Blandas")

    pt_blando = 0
    for i, p in enumerate(PREGUNTAS_BLANDAS):
        r = st.radio(p, ["S", "N"], key=f"bla_{i}")
        if r == "S":
            pt_blando += 1

    # --- Cálculo ---
    porcentaje_blando = pt_blando / len(PREGUNTAS_BLANDAS)
    aprobado = porcentaje_blando >= PUNTAJE_MINIMO_BLANDAS

    st.write("---")

    if st.button("Guardar evaluación"):
        if nombre == "" or correo == "":
            st.error("Faltan datos del candidato.")
        else:
            documento = {
                "nombre": nombre,
                "correo": correo,
                "edad": edad,
                "tecnico": pt_tecnico,
                "blandas": pt_blando,
                "porcentaje_blandas": round(porcentaje_blando, 2),
                "aprobado": aprobado,
                "fecha_registro": datetime.now()
            }

            col.insert_one(documento)
            st.success("✔️ Evaluación guardada en MongoDB correctamente.")


# =========================================
# 5. PÁGINA: VER CANDIDATOS
# =========================================
if pagina == "Ver candidatos":
    st.title("📋 Ver Candidatos Registrados")

    # Filtros
    correo_f = st.text_input("Buscar por correo contiene:")
    min_tecnico = st.number_input("Mínimo puntaje técnico", 0, len(PREGUNTAS_TECNICAS), 0)
    min_blandas = st.number_input("Mínimo puntaje blandas", 0, len(PREGUNTAS_BLANDAS), 0)
    solo_aprobados = st.checkbox("Mostrar solo aprobados")

    query = {}

    if correo_f:
        query["correo"] = {"$regex": correo_f, "$options": "i"}

    if min_tecnico > 0:
        query["tecnico"] = {"$gte": min_tecnico}

    if min_blandas > 0:
        query["blandas"] = {"$gte": min_blandas}

    if solo_aprobados:
        query["aprobado"] = True

    # Obtener datos
    datos = list(col.find(query, {"_id": 0}))

    if len(datos) == 0:
        st.warning("No se encontraron candidatos con esos filtros.")
    else:
        df = pd.DataFrame(datos)
        st.dataframe(df)

        st.download_button(
            "Descargar en CSV",
            df.to_csv(index=False).encode("utf-8"),
            "candidatos.csv",
            "text/csv"
        )

MONGO_URI = "mongodb+srv://tavo_user:1234567#@cluster0.cjx2xfb.mongodb.net/?appName=Cluster0"