# -*- coding: utf-8 -*-
"""MUCHACHAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_aAcsinZ4vGNQYvbOTRASZFbYRj7X_ZN
"""

# -*- coding: utf-8 -*-
"""Versión optimizada del sistema de selección BRICOS"""

import base64
import os
import secrets # Usamos secrets para una generación de tokens más robusta/segura
from collections import defaultdict # Para un conteo más limpio

# --- PARÁMETROS ---
NUM_PREGUNTAS_TECNICAS = 12
NUM_PREGUNTAS_BLANDAS = 13
PUNTAJE_MINIMO_BLANDAS = 0.75  # 75%

# --- CLAVE RSA SIMULADA MEJORADA (MUESTRA INTENCIÓN DE CLAVE REAL) ---
class RSAKeySimulada:
    """Clase para simular la generación de claves pública/privada."""
    def __init__(self):
        # Genera una clave pública (por ejemplo, 256 bits)
        self.public_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")
        # Genera una clave privada (no se usa, pero simula su existencia)
        self.private_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")

def cifrar_rsa_simulado(datos, clave_publica):
    """Simula el cifrado usando la clave pública."""
    # Simulación de un proceso de cifrado que devuelve un output más complejo
    datos_codificados = base64.urlsafe_b64encode(datos.encode("utf-8")).decode("utf-8")
    # Formato que simula un mensaje cifrado
    return f"RSA-256-CIPHER:{clave_publica[:16]}...{datos_codificados[:40]}..."

# --- PREGUNTAS (Se mantienen igual) ---
PREGUNTAS_TECNICAS = [
    "¿Sabe realizar inventarios físicos y conteos rápidos de material de construcción?", # 0
    "¿Ha utilizado algún software de Punto de Venta (POS) o sistema de facturación electrónica?", # 1
    "¿Sabe leer e interpretar una hoja de ruta o usar GPS para optimizar entregas?", # 2
    "¿Tiene experiencia o conoce el manejo básico de un montacargas o patín hidráulico?", # 3
    "¿Puede identificar y diferenciar los tipos de cemento, varilla y arena comunes en la construcción?", # 4
    "¿Sabe cómo se calcula el volumen o área de un material (ej. m³ de arena, m² de loseta)?", # 5
    "¿Se siente cómodo manejando una terminal bancaria y realizando cobros con tarjeta?", # 6
    "¿Puede verificar y cotejar una orden de compra contra el material físico que se va a cargar?", # 7
    "¿Conoce las normas básicas de seguridad para cargar y descargar materiales pesados?", # 8
    "¿Tiene conocimientos básicos de uso de hojas de cálculo (Excel, Google Sheets) para reportes?", # 9
    "¿Sabe realizar el mantenimiento básico o limpieza de herramientas y equipos de trabajo?", # 10
    "¿Puede calcular rápidamente el cambio para un pago en efectivo?" # 11
]

PREGUNTAS_BLANDAS = [
    "¿Mantiene la calma y es cortés al tratar con un cliente enojado o impaciente?",
    "¿Se adapta fácilmente a los cambios de tareas o prioridades de última hora?",
    "¿Ofrece ayuda a sus compañeros sin que se lo pidan?",
    "¿Es puntual y respeta estrictamente los horarios?",
    "¿Acepta retroalimentación sin ponerse a la defensiva?",
    "¿Se enfoca en soluciones en lugar de culpar a otros?",
    "¿Es proactivo buscando tareas pendientes?",
    "¿Se comunica de manera clara y concisa?",
    "¿Trabaja bien bajo presión?",
    "¿Su honestidad y ética son inquebrantables?",
    "¿Prioriza la seguridad ante todo?",
    "¿Propone mejoras a procesos ineficientes?",
    "¿Se siente cómodo pidiendo al cliente verificar la carga/ticket?"
]

# --- ASIGNACIÓN DE ÁREA POR HABILIDADES ---
AREAS = {
    # El índice corresponde a la pregunta en PREGUNTAS_TECNICAS
    "CARGADOR":         [0, 3, 4, 7, 8],
    "VENTAS/COBRANZA":  [1, 6, 11],
    "REPARTIDOR":       [2, 3, 7, 8],
    "LIMPIEZA":         [10],
    "ADMINISTRATIVO":   [9, 1, 5] # Agregamos un par de preguntas relevantes para Admin
}

# La función se mantiene igual, asigna el área con más coincidencias 'S'
def asignar_area(respuestas):
    """Asigna el área técnica con el mayor número de coincidencias 'S'."""
    conteo = defaultdict(int)
    for area, indices in AREAS.items():
        # Cuenta las respuestas 'S' solo para las preguntas relevantes del área
        conteo[area] = sum(1 for i in indices if i < len(respuestas) and respuestas[i] == "S")

    # Si todas las respuestas son 'N', devuelve el área con la lista de preguntas más larga como default
    if not any(conteo.values()):
        return max(AREAS, key=lambda a: len(AREAS[a]))

    return max(conteo, key=conteo.get)


# --- SELECCIÓN DE ÁREA DESEADA (Se mantiene igual) ---
def seleccionar_area_deseada():
    opciones = {
        "1": "CARGADOR",
        "2": "VENTAS/COBRANZA",
        "3": "REPARTIDOR",
        "4": "LIMPIEZA",
        "5": "ADMINISTRATIVO"
    }

    print("\n--- SELECCIONA EL PUESTO AL QUE DESEAS APLICAR ---")
    for k, v in opciones.items():
        print(f"{k}. {v}")

    while True:
        eleccion = input("Elige una opción (1-5): ").strip()
        if eleccion in opciones:
            return opciones[eleccion]
        print("Opción no válida. Intenta nuevamente.")

# --- DATOS PERSONALES (Se mantiene igual) ---
def pedir_datos_personales():
    def pedir_campo(mensaje, obligatorio=True):
        while True:
            valor = input(mensaje).strip()
            if valor or not obligatorio:
                return valor
            print("Este campo no puede quedar vacío.")

    print("--- DATOS PERSONALES ---")
    datos = {
        "nombre": pedir_campo("Nombre completo: "),
        "edad": pedir_campo("Edad: "),
        "sexo": pedir_campo("Sexo (M/F/Otro): "),
        "correo": pedir_campo("Correo electrónico (Será cifrado): "),
        "telefono": pedir_campo("Número de teléfono (Será cifrado): ")
    }
    return datos

# --- CUESTIONARIO (REUTILIZABLE, se mantiene igual) ---
def realizar_cuestionario(preguntas, tipo):
    puntaje = 0
    respuestas = []

    print(f"\n--- HABILIDADES {tipo.upper()} ({len(preguntas)} preguntas) ---")

    for i, pregunta in enumerate(preguntas):
        while True:
            r = input(f"❓ {i+1}. {pregunta} (S/N): ").upper().strip()
            if r in ("S", "N"):
                respuestas.append(r)
                if r == "S":
                    puntaje += 1
                break
            print("Respuesta inválida. Solo S o N.")
    return puntaje, respuestas

# --- EVALUACIÓN (Se mantiene igual) ---
def evaluar_resultados(pt_tecnico, pt_blando):
    pct_tec = (pt_tecnico / NUM_PREGUNTAS_TECNICAS) * 100
    pct_bla = (pt_blando / NUM_PREGUNTAS_BLANDAS) * 100
    # La aceptación se basa estrictamente en el puntaje blando (75%)
    es_aceptado = pct_bla >= (PUNTAJE_MINIMO_BLANDAS * 100)
    return es_aceptado, pct_tec, pct_bla

# --- PROCESO PRINCIPAL ---
def iniciar_proceso_seleccion():
    print("=====================================================")
    print("     🌟 MUCHACHAM 🌟")
    print("=====================================================")

    datos = pedir_datos_personales()
    area_deseada = seleccionar_area_deseada()

    # Cifrado simulado MEJORADO
    key_generator = RSAKeySimulada()
    datos_cifrados = cifrar_rsa_simulado(
        f"Email:{datos['correo']}|Tel:{datos['telefono']}",
        key_generator.public_key
    )
    print("✅ Datos de contacto cifrados con RSA simulado (Clave Pública generada).")

    # Cuestionarios
    pt_tecnico, resp_tecnicas = realizar_cuestionario(PREGUNTAS_TECNICAS, "TÉCNICAS")
    pt_blando, _ = realizar_cuestionario(PREGUNTAS_BLANDAS, "BLANDAS")

    # Evaluación final
    aceptado, pct_tec, pct_bla = evaluar_resultados(pt_tecnico, pt_blando)

    # El error de "siempre ir a cargador" no estaba en la lógica de 'asignar_area',
    # sino en la percepción de que la baja puntuación blanda forzaba el resultado.
    # El área recomendada SOLO depende de las respuestas TÉCNICAS.
    area_recomendada = asignar_area(resp_tecnicas)

    # Resultados
    print("\n================= RESULTADO FINAL =================")
    print(f"**Puesto Deseado:**   {area_deseada}") # <-- CORRECCIÓN A: Mostrar el puesto deseado
    print(f"**Área Recomendada:** {area_recomendada}")
    print("---------------------------------------------------")
    print(f"TÉCNICAS: {pt_tecnico}/{NUM_PREGUNTAS_TECNICAS} ({pct_tec:.2f}%)")
    print(f"BLANDAS:  {pt_blando}/{NUM_PREGUNTAS_BLANDAS} ({pct_bla:.2f}%) (Mínimo requerido: {PUNTAJE_MINIMO_BLANDAS*100:.0f}%)")
    print("---------------------------------------------------")

    # Mostrar estado de aceptación
    if aceptado:
        print("ESTADO FINAL: **✅ ACEPTADO**")
    else:
        print("ESTADO FINAL: **❌ NO ACEPTADO** (Fallo en puntaje BLANDO)")

    # Coincidencia de áreas
    if area_recomendada == area_deseada:
        print("⭐ ¡Felicidades! Coincide el área deseada con tu perfil técnico.")
    else:
        print(f"💡 Sugerencia: El área **{area_recomendada}** es un mejor ajuste según tus habilidades técnicas.")

    print("\n================= REGISTRO DE DATOS =================")
    print(f"Nombre: {datos['nombre']} | Edad: {datos['edad']}")
    print(f"DATOS CIFRADOS (simulación): {datos_cifrados}")
    print("=====================================================")

# Ejecutar el programa
if __name__ == "__main__":
    iniciar_proceso_seleccion()