# -*- coding: utf-8 -*-
"""MUCHACHAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACuxg_aod4NtOrZqACHQV2bgW31eEWxr
"""

import streamlit as st
import base64
import secrets
from collections import defaultdict

# --- PARÁMETROS ---
NUM_PREGUNTAS_TECNICAS = 12
NUM_PREGUNTAS_BLANDAS = 13
PUNTAJE_MINIMO_BLANDAS = 0.75  # 75%

# --- CLAVE RSA SIMULADA ---
class RSAKeySimulada:
    def __init__(self):
        self.public_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")
        self.private_key = base64.b64encode(secrets.token_bytes(32)).decode("utf-8")

def cifrar_rsa_simulado(datos, clave_publica):
    datos_codificados = base64.urlsafe_b64encode(datos.encode("utf-8")).decode("utf-8")
    return f"RSA-256-CIPHER:{clave_publica[:16]}...{datos_codificados[:40]}..."

# --- PREGUNTAS ---
PREGUNTAS_TECNICAS = [
    "¿Sabe realizar inventarios físicos y conteos rápidos de material de construcción?",
    "¿Ha utilizado algún software de Punto de Venta (POS) o sistema de facturación electrónica?",
    "¿Sabe leer e interpretar una hoja de ruta o usar GPS para optimizar entregas?",
    "¿Tiene experiencia o conoce el manejo básico de un montacargas o patín hidráulico?",
    "¿Puede identificar y diferenciar los tipos de cemento, varilla y arena comunes en la construcción?",
    "¿Sabe cómo se calcula el volumen o área de un material?",
    "¿Se siente cómodo manejando una terminal bancaria y realizando cobros con tarjeta?",
    "¿Puede verificar y cotejar una orden de compra contra el material físico?",
    "¿Conoce normas básicas de seguridad en carga/descarga?",
    "¿Tiene conocimientos básicos de Excel o Google Sheets?",
    "¿Sabe realizar mantenimiento básico o limpieza de herramientas?",
    "¿Puede calcular rápidamente el cambio en efectivo?"
]

PREGUNTAS_BLANDAS = [
    "¿Mantiene la calma ante clientes difíciles?",
    "¿Se adapta fácilmente a cambios?",
    "¿Ofrece ayuda sin que se lo pidan?",
    "¿Es puntual?",
    "¿Acepta retroalimentación?",
    "¿Busca soluciones en lugar de culpas?",
    "¿Es proactivo?",
    "¿Se comunica claramente?",
    "¿Trabaja bien bajo presión?",
    "¿Es completamente honesto?",
    "¿Prioriza la seguridad?",
    "¿Propone mejoras?",
    "¿Pide al cliente verificar carga/ticket?"
]

AREAS = {
    "CARGADOR":         [0, 3, 4, 7, 8],
    "VENTAS/COBRANZA":  [1, 6, 11],
    "REPARTIDOR":       [2, 3, 7, 8],
    "LIMPIEZA":         [10],
    "ADMINISTRATIVO":   [9, 1, 5]
}

def asignar_area(respuestas):
    conteo = defaultdict(int)
    for area, indices in AREAS.items():
        conteo[area] = sum(1 for i in indices if respuestas[i] == "S")
    if not any(conteo.values()):
        return max(AREAS, key=lambda a: len(AREAS[a]))
    return max(conteo, key=conteo.get)

def evaluar_resultados(pt_tecnico, pt_blando):
    pct_tec = (pt_tecnico / NUM_PREGUNTAS_TECNICAS) * 100
    pct_bla = (pt_blando / NUM_PREGUNTAS_BLANDAS) * 100
    es_aceptado = pct_bla >= (PUNTAJE_MINIMO_BLANDAS * 100)
    return es_aceptado, pct_tec, pct_bla

# --- STREAMLIT APP ---
st.title("🌟 Sistema de Selección BRICOS (WebApp)")

st.header("1. Datos personales")
nombre = st.text_input("Nombre completo")
edad = st.text_input("Edad")
sexo = st.selectbox("Sexo", ["M", "F", "Otro"])
correo = st.text_input("Correo electrónico")
telefono = st.text_input("Número telefónico")

st.header("2. Puesto deseado")
puesto = st.selectbox(
    "Selecciona el puesto al que deseas aplicar",
    ["CARGADOR", "VENTAS/COBRANZA", "REPARTIDOR", "LIMPIEZA", "ADMINISTRATIVO"]
)

st.header("3. Cuestionario Técnico")
respuestas_tecnicas = []
pt_tecnico = 0
for i, p in enumerate(PREGUNTAS_TECNICAS):
    r = st.radio(p, ["S", "N"], key=f"tec_{i}")
    respuestas_tecnicas.append(r)
    if r == "S":
        pt_tecnico += 1

st.header("4. Cuestionario de Habilidades Blandas")
pt_blando = 0
for i, p in enumerate(PREGUNTAS_BLANDAS):
    r = st.radio(p, ["S", "N"], key=f"bla_{i}")
    if r == "S":
        pt_blando += 1

if st.button("🟦 Evaluar Candidato"):
    keygen = RSAKeySimulada()
    datos_cifrados = cifrar_rsa_simulado(
        f"Email:{correo}|Tel:{telefono}",
        keygen.public_key
    )

    aceptado, pct_tec, pct_bla = evaluar_resultados(pt_tecnico, pt_blando)
    area_recomendada = asignar_area(respuestas_tecnicas)

    st.subheader("📌 RESULTADO FINAL")
    st.write(f"**Puesto deseado:** {puesto}")
    st.write(f"**Área recomendada:** {area_recomendada}")
    st.write(f"**Técnicas:** {pt_tecnico} / {NUM_PREGUNTAS_TECNICAS} → {pct_tec:.2f}%")
    st.write(f"**Blandas:** {pt_blando} / {NUM_PREGUNTAS_BLANDAS} → {pct_bla:.2f}%")

    if aceptado:
        st.success("✅ ACEPTADO")
    else:
        st.error("❌ NO ACEPTADO (fallo en habilidades blandas)")

    if area_recomendada == puesto:
        st.info("⭐ Tu perfil técnico coincide con tu puesto deseado.")
    else:
        st.warning(f"💡 Sugerencia: {area_recomendada} es mejor ajuste según tus habilidades.")

    st.subheader("🔐 Datos cifrados:")
    st.code(datos_cifrados)