# -*- coding: utf-8 -*-
"""pp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbyvnZv6n-cLtW1BXrDagJMrbfVoO3xE
"""

!pip install cryptography
# -*- coding: utf-8 -*-
"""Versión completa con MongoDB + correcciones de Sí/No + Cifrado AES-256 Real"""
!pip install dnspython
!pip install streamlit pymongo[srv]
!pip install cryptography

import random
import base64
import secrets
from collections import defaultdict
from pymongo import MongoClient
# 🐍 Nuevos imports para Cifrado
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

# ================================
# 🔵  CONEXIÓN A MONGODB
# ================================
# ⚠️ REEMPLAZA TU CADENA DE MONGODB AQUÍ
MONGO_URI = "mongodb+srv://tavo_user:1234567#@cluster0.cjx2xfb.mongodb.net/?appName=Cluster0"
client = MongoClient(MONGO_URI)
db = client["bricos_db"]
coleccion = db["candidatos"]

# ================================
# 🔵  PARÁMETROS
# ================================
NUM_PREGUNTAS_TECNICAS = 12
NUM_PREGUNTAS_BLANDAS = 13
PUNTAJE_MINIMO_BLANDAS = 0.45

# ================================
# 🔵  CLASE DE CIFRADO SIMÉTRICO (AES)
# ================================
class AESCipher:
    """Clase para cifrar y descifrar usando AES-256."""
    def __init__(self):
        # Generar una clave "pública" simulada y un salt único para la derivación
        self.salt = secrets.token_bytes(16)
        self.public_key = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("utf-8")

        # 1. Derivar la clave AES (32 bytes = 256 bits)
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=self.salt,
            iterations=480000, # Alto número de iteraciones para resistencia (KDF)
            backend=default_backend()
        )
        self.key = kdf.derive(self.public_key.encode("utf-8"))

    def cifrar(self, datos):
        """Cifra los datos usando AES-256 en modo GCM (con autenticación)."""
        datos_bytes = datos.encode("utf-8")
        iv = secrets.token_bytes(12) # Initialization Vector (IV)

        # Cifrador GCM (Galois Counter Mode)
        cipher = Cipher(algorithms.AES(self.key), modes.GCM(iv), backend=default_backend())
        encryptor = cipher.encryptor()

        ciphertext = encryptor.update(datos_bytes) + encryptor.finalize()
        tag = encryptor.tag

        # Concatenar IV, Salt, Tag y texto cifrado. Luego codificar en Base64.
        datos_cifrados = iv + self.salt + tag + ciphertext
        return base64.urlsafe_b64encode(datos_cifrados).decode("utf-8")

# ================================
# 🔵  PREGUNTAS TÉCNICAS
# ================================
PREGUNTAS_TECNICAS = [
    "¿Sabe realizar inventarios físicos y conteos rápidos de material de construcción?",
    "¿Ha utilizado algún software de Punto de Venta (POS) o sistema de facturación electrónica?",
    "¿Sabe leer e interpretar una hoja de ruta o usar GPS para optimizar entregas?",
    "¿Tiene experiencia o conoce el manejo básico de un montacargas o patín hidráulico?",
    "¿Puede identificar y diferenciar los tipos de cemento, varilla y arena comunes en la construcción?",
    "¿Sabe cómo se calcula el volumen o área de un material (ej. m³ de arena, m² de loseta)?",
    "¿Se siente cómodo manejando una terminal bancaria y realizando cobros con tarjeta?",
    "¿Puede verificar y cotejar una orden de compra contra el material físico que se va a cargar?",
    "¿Conoce las normas básicas de seguridad para cargar y descargar materiales pesados?",
    "¿Tiene conocimientos básicos de uso de hojas de cálculo (Excel, Google Sheets) para reportes?",
    "¿Sabe realizar el mantenimiento básico o limpieza de herramientas y equipos de trabajo?",
    "¿Puede calcular rápidamente el cambio para un pago en efectivo?"
]

PREGUNTAS_BLANDAS = [
    "¿Mantiene la calma y es cortés al tratar con un cliente enojado o impaciente?",
    "¿Se adapta fácilmente a los cambios de tareas o prioridades de última hora?",
    "¿Ofrece ayuda a sus compañeros sin que se lo pidan?",
    "¿Es puntual y respeta estrictamente los horarios?",
    "¿Acepta retroalimentación sin ponerse a la defensiva?",
    "¿Se enfoca en soluciones en lugar de culpar a otros?",
    "¿Es proactivo buscando tareas pendientes?",
    "¿Se comunica de manera clara y concisa?",
    "¿Trabaja bien bajo presión?",
    "¿Su honestidad y ética son inquebrantables?",
    "¿Prioriza la seguridad ante todo?",
    "¿Propone mejoras a procesos ineficientes?",
    "¿Se siente cómodo pidiendo al cliente verificar la carga/ticket?"
]

# ================================
# 🔵  ÁREAS
# ================================
AREAS = {
    "CARGADOR":        [0, 3, 4, 7, 8],
    "VENTAS/COBRANZA": [1, 6, 11],
    "REPARTIDOR":      [2, 3, 7, 8],
    "LIMPIEZA":        [10],
    "ADMINISTRATIVO":  [9, 1, 5]
}

def asignar_area(respuestas):
    conteo = defaultdict(int)
    for area, indices in AREAS.items():
        conteo[area] = sum(1 for i in indices if respuestas[i] == "Sí")

    if not any(conteo.values()):
        return max(AREAS, key=lambda a: len(AREAS[a]))

    return max(conteo, key=conteo.get)

# ================================
# 🔵  SELECCIÓN DE ÁREA DESEADA
# ================================
def seleccionar_area_deseada():
    opciones = {
        "1": "CARGADOR",
        "2": "VENTAS/COBRANZA",
        "3": "REPARTIDOR",
        "4": "LIMPIEZA",
        "5": "ADMINISTRATIVO"
    }

    print("\n--- PUESTO AL QUE DESEAS APLICAR ---")
    for k, v in opciones.items():
        print(f"{k}. {v}")

    while True:
        eleccion = input("Elige una opción (1-5): ").strip()
        if eleccion in opciones:
            return opciones[eleccion]
        print("Opción no válida.")

# ================================
# 🔵  DATOS PERSONALES
# ================================
def pedir_datos_personales():
    def pedir(m):
        while True:
            x = input(m).strip()
            if x: # Added condition and colon here
                return x
            print("No puede quedar vacío.")